services:
  db:
    image: postgres:16
    container_name: quizzfly-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ:-UTC}
      PGTZ: ${PGTZ:-UTC}
    ports:
      - '25432:5432'
    networks:
      - quizzfly-network

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: quizzfly-redis
    hostname: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis_data:/data
    networks:
      - quizzfly-network

  quizzfly-api:
    image: quizzfly-api
    container_name: quizzfly-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    expose:
      - ${APP_PORT}
    depends_on:
      - db
      - redis
    networks:
      - quizzfly-network

  pgadmin:
    container_name: quizzfly-pgadmin
    image: dpage/pgadmin4
    ports:
      - '18080:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
    networks:
      - quizzfly-network

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:

networks:
  quizzfly-network:
    driver: bridge
