services:
  quizzfly-api:
    image: quizzfly-api-local
    container_name: quizzfly-api-local
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    command: npm start:dev
    networks:
      - quizzfly-network

  db:
    image: postgres:16
    container_name: quizzfly-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quizzfly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - quizzfly-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - quizzfly-network

volumes:
  postgres_data:

networks:
  quizzfly-network:
    driver: bridge
