services:
  db:
    image: postgres:16
    container_name: quizzfly-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: quizzfly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - quizzfly-network

  redis:
    image: redis:latest
    container_name: redis-container
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - quizzfly-network

  quizzfly-api:
    image: quizzfly-api
    container_name: quizzfly-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - quizzfly-network

volumes:
  postgres_data:

networks:
  quizzfly-network:
    driver: bridge
